version: "3"

services:
  etcd-n1:
    image:
      gcr.io/etcd-development/etcd
    container_name:
      etcd-node-1
    restart: always
    # networks: 
    #   etcd_cluster_net:
    #     ipv4_address: 202.111.14.11
    ports:
      - 12379:2379
      - 12380:2380
    volumes:
      - ./node1/data:/data
    command:
      etcd
      --name=etcd-node-1
      --data-dir=/data
      --log-output stdout
      --listen-client-urls http://0.0.0.0:2379
      --listen-peer-urls http://0.0.0.0:2380
      --initial-advertise-peer-urls http://etcd-n1:2380
      --advertise-client-urls http://etcd-n1:2379
      --initial-cluster etcd-node-1=http://etcd-n1:2380,etcd-node-2=http://etcd-n2:2380,etcd-node-3=http://etcd-n3:2380
      --initial-cluster-state new
      --initial-cluster-token my-etcd-cluster
  
  etcd-n2:
    image:
      gcr.io/etcd-development/etcd
    container_name:
      etcd-node-2
    restart: always
    # networks: 
    #   etcd_cluster_net:
    #     ipv4_address: 202.111.14.12
    ports:
      - 22379:2379
      - 22380:2380
    volumes:
      - ./node2/data:/data
    command:
      etcd
      --name=etcd-node-2
      --data-dir=/data
      --log-output stdout
      --listen-client-urls http://0.0.0.0:2379
      --listen-peer-urls http://0.0.0.0:2380
      --initial-advertise-peer-urls http://etcd-n2:2380
      --advertise-client-urls http://etcd-n2:2379
      --initial-cluster etcd-node-1=http://etcd-n1:2380,etcd-node-2=http://etcd-n2:2380,etcd-node-3=http://etcd-n3:2380
      --initial-cluster-state new
      --initial-cluster-token my-etcd-cluster
    
  etcd-n3:
    image:
      gcr.io/etcd-development/etcd
    container_name:
      etcd-node-3
    restart: always
    # networks: 
    #   etcd_cluster_net:
    #     ipv4_address: 202.111.14.13
    ports:
      - 32379:2379
      - 32380:2380
    volumes:
      - ./node3/data:/data
    command:
      etcd
      --name=etcd-node-3
      --data-dir=/data
      --log-output stdout
      --listen-client-urls http://0.0.0.0:2379
      --listen-peer-urls http://0.0.0.0:2380
      --initial-advertise-peer-urls http://etcd-n3:2380
      --advertise-client-urls http://etcd-n3:2379
      --initial-cluster etcd-node-1=http://etcd-n1:2380,etcd-node-2=http://etcd-n2:2380,etcd-node-3=http://etcd-n3:2380
      --initial-cluster-state new
      --initial-cluster-token my-etcd-cluster

# networks: 
#   etcd_cluster_net:
#     driver: bridge
#     ipam:
#       config:
#         - subnet: 202.111.14.0/24